
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: onlineboutique
components:
- base/for-memorystore
- base/for-virtualservice-host
- sidecars/for-namespace
- ../upstream/sidecars/for-memorystore
- authorization-policies/for-namespace
- authorization-policies/for-ingress-gateway
